let musicas = [
    {id: 1, nome: 'Ariana Grande', musicName: 'Positions', album: 'Positions', tempo: 2+':'+58, foto: 'images/ariana.png', musica:'musics/Ariana-positions.mp3'},
    {id: 2, nome: 'Ariana Grande', musicName: 'Thank u, next', album: 'Thank u, Next', tempo: 3+':'+27, foto: 'images/tank.png', musica:'musics/Ariana Grande - thank u, next.mp3'},
    {id: 3, nome: 'DaBaby', musicName: 'BOP', album: 'KIRK', tempo: 2+':'+40, foto: 'images/bopp.png', musica:'musics/Dababy - BOP.mp3'},
    {id: 4, nome: 'DaBaby', musicName: 'Rockstar', album: 'KIRK', tempo: 3+':'+"0"+1, foto: 'images/rock.png', musica:'musics/Dababy - ROCKSTAR.mp3'},
    {id: 5, nome: 'Lil Tecca', musicName: 'Ransom', album: 'We Love You Tecca', tempo: 2+':'+12, foto: 'images/wordteca.png', musica:'musics/Lil Tecca - Ransom.mp3'},
    {id: 6, nome: 'Lil Tecca', musicName: 'Never Left', album: 'We Love You Tecca', tempo: 2+':'+46, foto: 'images/wordteca.png', musica:'musics/Lil Tecca - Never Left.mp3'},
    {id: 7, nome: 'Killbunk', musicName: 'Chanel Bag', album: 'Chanel Bag', tempo: 2+':'+39, foto: 'images/bag.png', musica:'musics/Killbunk - Chanel Bag.mp3'},
    {id: 8, nome: 'Killbunk', musicName: 'Nascar', album: 'Chanel Bag', tempo: 1+':'+54, foto: 'images/bascar.png', musica:'musics/Killbunk - Nascar.mp3'},
    {id: 9, nome: 'Alok', musicName: 'Favela', album: 'Alok', tempo: 3+':'+"0"+5, foto: 'images/fav.png', musica:'musics/Alok - Favela.mp3'},
    {id: 10, nome: 'Alok', musicName: 'Meduza', album: 'Alok', tempo: 2+':'+32, foto: 'images/piece.png', musica:'musics/Alok - Meduza.mp3'},
    {id: 11, nome: 'Lil Nas X', musicName: 'Industry Baby', album: 'MONTERO', tempo: 3+':'+55, foto: 'images/montero.png', musica:'musics/Lil Nas X - Industry Baby.mp3'},
    {id: 12, nome: 'Lil Nas X', musicName: 'Call Me By Your Name', album: 'MONTERO', tempo: 3+':'+'0'+9, foto: 'images/montero.png', musica:'musics/Lil Nas X - MONTERO (Call Me By Your Name).mp3'},
    {id: 13, nome: 'Lil Nas X', musicName: 'Dolla Sign Slime', album: 'MONTERO', tempo: 2+':'+26, foto: 'images/montero.png', musica:'musics/Lil Nas X - DOLLA SIGN SLIME.mp3'},
    {id: 14, nome: 'Lil Nas X', musicName: 'Thats What I Want', album: 'MONTERO', tempo: 2+':'+42, foto: 'images/montero.png', musica:'musics/Lil Nas X-th.mp3'},
    {id: 15, nome: 'Lil Nas X', musicName: 'Dont Want It', album: 'MONTERO', tempo: 2+':'+11, foto: 'images/montero.png', musica:'musics/Lil Nas X - DONT WANT IT.mp3'},
    {id: 16, nome: 'Poze Do Rodo', musicName: 'Vida Louca', album: 'Vida Louca', tempo: 3+':'+'0'+3, foto: 'images/poze.png', musica:'musics/MC Poze do Rodo - Vida Louca.mp3'},
    {id: 17, nome: 'Ariana Grande.', musicName: '34+35', album: 'Positions', tempo: 3+':'+40, foto: 'images/ariana.png', musica:'musics/Ariana Grande - 34+35.mp3'},
    {id: 18, nome: 'Ayo & Teo', musicName: 'Fly N Ghetto', album: 'Fly N Ghetto', tempo: 2+':'+29, foto: 'images/geto.png', musica:'musics/Ayo & Teo - Fly N Ghetto.mp3'},
    {id: 19, nome: 'Drake', musicName: 'Toosie Slide', album: 'Toosie Slide', tempo: 4+':'+48, foto: 'images/tosie.png', musica:'musics/Drake - Toosie Slide.mp3'},
    {id: 20, nome: 'Soulja Boy', musicName: 'Kiss Me Thru The Phone', album: 'iSouljaBoyTellEm', tempo: 3+':'+15, foto: 'images/ksme.png', musica:'musics/Soulja Boy -Kiss Me.mp3'},
    {id: 21, nome: 'Chris Brown', musicName: 'Kiss Kiss', album: 'Exclusive', tempo: 4+':'+18, foto: 'images/meme.png', musica:'musics/Chris Brown - Kiss Kiss.mp3'},
]

